server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: msa_user
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/msa_sample
    username: ${DB_USER}
    password: ${DB_PASS}
